package com.ceos.s7.sapi;

import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 578</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class S7_ADD_VALUE extends Structure {
	/// C type : ord16
	public short data_type;
	/// C type : ord16
	public short add_value_len;
	/// C type : ord8[432 + 2]
	public byte[] value = new byte[432 + 2];
	public S7_ADD_VALUE() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"data_type", "add_value_len", "value"});
	}
	/**
	 * @param data_type C type : ord16<br>
	 * @param add_value_len C type : ord16<br>
	 * @param value C type : ord8[432 + 2]
	 */
	public S7_ADD_VALUE(short data_type, short add_value_len, byte value[]) {
		super();
		this.data_type = data_type;
		this.add_value_len = add_value_len;
		if (value.length != this.value.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.value = value;
		initFieldOrder();
	}
	public static class ByReference extends S7_ADD_VALUE implements Structure.ByReference {
		
	};
	public static class ByValue extends S7_ADD_VALUE implements Structure.ByValue {
		
	};
        
        @Override
        protected List getFieldOrder() {
            return Arrays.asList(new String[]{"data_type", "add_value_len", "value"});
        }           
}
