package com.ceos.s7.sapi;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 510</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class S7_READ_PARA extends Structure {
	/// C type : ord16
	public short access;
	/// C type : char[32 + 2]
	public byte[] var_name = new byte[32 + 2];
	/// C type : ord16
	public short index;
	/// C type : ord16
	public short subindex;
	/// C type : ord16
	public short address_len;
	/// C type : ord8[32]
	public byte[] address = new byte[32];
	public S7_READ_PARA() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"access", "var_name", "index", "subindex", "address_len", "address"});
	}
	/**
	 * @param access C type : ord16<br>
	 * @param var_name C type : char[32 + 2]<br>
	 * @param index C type : ord16<br>
	 * @param subindex C type : ord16<br>
	 * @param address_len C type : ord16<br>
	 * @param address C type : ord8[32]
	 */
	public S7_READ_PARA(short access, byte var_name[], short index, short subindex, short address_len, byte address[]) {
		super();
		this.access = access;
		if (var_name.length != this.var_name.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.var_name = var_name;
		this.index = index;
		this.subindex = subindex;
		this.address_len = address_len;
		if (address.length != this.address.length) 
			throw new IllegalArgumentException("Wrong array size !");
		this.address = address;
		initFieldOrder();
	}
	public static class ByReference extends S7_READ_PARA implements Structure.ByReference {
		
	};
	public static class ByValue extends S7_READ_PARA implements Structure.ByValue {
		
	};
        
        @Override
        protected List getFieldOrder() {
            return Arrays.asList(new String[]{"access", "var_name", "index", "subindex", "address_len", "address"});
        }           
}
