package com.ceos.s7.sapi;

import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : line 552</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class S7_TIME_STAMP extends Structure {
	/// C type : ord16
	public short year;
	/// C type : ord16
	public short month;
	/// C type : ord16
	public short day;
	/// C type : ord16
	public short week_day;
	/// C type : ord16
	public short hour;
	/// C type : ord16
	public short minute;
	/// C type : ord16
	public short second;
	/// C type : ord16
	public short millisecond;
	public S7_TIME_STAMP() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"year", "month", "day", "week_day", "hour", "minute", "second", "millisecond"});
	}
	/**
	 * @param year C type : ord16<br>
	 * @param month C type : ord16<br>
	 * @param day C type : ord16<br>
	 * @param week_day C type : ord16<br>
	 * @param hour C type : ord16<br>
	 * @param minute C type : ord16<br>
	 * @param second C type : ord16<br>
	 * @param millisecond C type : ord16
	 */
	public S7_TIME_STAMP(short year, short month, short day, short week_day, short hour, short minute, short second, short millisecond) {
		super();
		this.year = year;
		this.month = month;
		this.day = day;
		this.week_day = week_day;
		this.hour = hour;
		this.minute = minute;
		this.second = second;
		this.millisecond = millisecond;
		initFieldOrder();
	}
	public static class ByReference extends S7_TIME_STAMP implements Structure.ByReference {
		
	};
	public static class ByValue extends S7_TIME_STAMP implements Structure.ByValue {
		
	};
        
        @Override
        protected List getFieldOrder() {
            return Arrays.asList(new String[]{"year", "month", "day", "week_day", "hour", "minute", "second", "millisecond"});
        }           
}
